# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e02606caf1b91913a3e81a3beeb520c7aba301dcdeb6fd50c3c497e7fb3847b55dfb1321480ad04f3931369e8430e3a2c798bc9bd5116fe8b9f825064b2b403

test:
  secret_key_base: 1f0cb1ae56f2bade82ee87286e567dcb4c450017f8f06900a30bc995d8b0511a944b72903f379db7903b556377d0ccca76f242613b6dd81686d159fc40bc5293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
